### ISSUE TITLE
Failed to open module dht_example.beam

### ISSUE THREAD

**Issue by ngomandat234** [atomvm/atomvm_dht#1]
Hi all,

When opening the monitor of esp32 I found that there was a line: Failed to open module dht_example.beam then crash. Module dht can not be resolved. Could you help me for this case?

Thanks a lot

**Comment by fadushin** [comment]
Hell @ngomandat234 .

Can you say more about what you have tried to do?

In order to make this project work, you will need to:

* Build a version of AtomVM with the `atomvm_dht` Nif included.  You will need to follow the build instructions on the AtomVM documentation page.
* Flash the VM image to your ESP32 device
* Build and flash the example program in this repo

I am not sure from what you have written what from the above steps you have tried or succeeded at.

Thanks!

**Comment by fadushin** [comment]
Note that I had some old changes I made to this repo that I neglected to commit, but I just committed and tested the code, so it should run once you get all the steps in order.  I have also updated some of the links in the docs, which had gone stale.

**Comment by ngomandat234** [comment]
Hi @fadushin,

Thanks a lot for your information.

That is my fault when not compiling the atomvn_dht nif included.  However, I try to include this nif and build again but it still failed

![a1](https://github.com/atomvm/atomvm_dht/assets/75436196/8d3cc20b-ac74-49ba-b7b1-98641b811f11)
![image](https://github.com/atomvm/atomvm_dht/assets/75436196/02e9c00a-3a69-409d-beb0-1bcddefe0e47)

I think it does not build with the atomvn_dht nif  successfully. 

Here is my step by step:
copy the atomvm_dht.c to AtomVM/src/platforms/esp32/components/avm_buildtins/
copy the include/atomvm_dht/h to AtomVM/src/platforms/esp32/components/avm_buildtins/include/
Add line atomvm_dht.c in AtomVM/src/platforms/esp32/components/avm_buildtins/CMakeLists.txt
Then AtomVM/src/platforms/esp32/build/mkimage.sh and AtomVM/src/platforms/esp32/build/flashimage.sh
Use rebar flash the atomvm_dht repo to the esp32.

Could you help quick check for me?

Thanks a lot!

**Comment by UncleGrumpy** [comment]
What you actually need to do is clone this entire repository into the AtomVM/src/platforms/esp32/components directory. Then re-configure the project with `idf.py menuconfig` and just quit, saving the changes if promoted. To make sure you have it set up correctly you can look near the bottom of the `components` menu in `menuconfig` and you should see a new `ATOMVM_DHT` component which should be enabled by default if you open that submenu. Hope this helps.

**Comment by ngomandat234** [comment]
Hi all,

It works for me. Many thanks @UncleGrumpy

**Comment by UncleGrumpy** [comment]
> Hi all,
> 
> 
> 
> It works for me. Many thanks @UncleGrumpy 

If you have no other problems would you mind closing the issue?

Unless you would like to make a suggestion about how we could make this more clear in our documentation, so we can help other users avoid this problem.
